const ADD_ROW = 'ADD_ROW'
const ADD_TOTAL = 'ADD_TOTAL'
const ADD_COINS_DATA = 'ADD_COINS_DATA'
const ADD_ALL_EXCHANGES = 'ADD_ALL_EXCHANGES'
const REWRITE_TABLE = 'REWRITE_TABLE'
const ADD_CBRF_CURRENCIES = 'ADD_CBRF_CURRENCIES'

const DELETE_ROW = 'DELETE_ROW'
const APPLY_ROW = 'APPLY_ROW'
const DECLINE_ROW = 'DECLINE_ROW'

const CHANGE_COIN = 'CHANGE_COIN'
const CHANGE_EXCHANGE = 'CHANGE_EXCHANGE'
const CHANGE_AMOUNT = 'CHANGE_AMOUNT'
const CHANGE_SECOND_CURRENCY = 'CHANGE_SECOND_CURRENCY'
const SORTING = 'SORTING'

const REQUEST_COINS_LIST = 'REQUEST_COINS_LIST'
const RESPONSE_COINS_LIST = 'RESPONSE_COINS_LIST'
const REQUEST_EXCHANGES = 'REQUEST_EXCHANGES'
const RESPONSE_EXCHANGES = 'RESPONSE_EXCHANGES'

const WS_SUBSCRIBE = 'WS_SUBSCRIBE'
const WS_UNSUBSCRIBE = 'WS_UNSUBSCRIBE'

const GET_START_DATA = 'GET_START_DATA'

export {
  ADD_ROW,
  ADD_TOTAL,
  ADD_COINS_DATA,
  ADD_ALL_EXCHANGES,
  REWRITE_TABLE,
  ADD_CBRF_CURRENCIES,
  DELETE_ROW,
  APPLY_ROW,
  DECLINE_ROW,
  CHANGE_COIN,
  CHANGE_EXCHANGE,
  CHANGE_AMOUNT,
  CHANGE_SECOND_CURRENCY,
  REQUEST_COINS_LIST,
  RESPONSE_COINS_LIST,
  REQUEST_EXCHANGES,
  RESPONSE_EXCHANGES,
  WS_UNSUBSCRIBE,
  SORTING
}